### ISSUE TITLE
我的集数不显示封面播放会有缓冲

### ISSUE THREAD

**Issue by make858** [ourfor/iPlay#157]
服务端是emby4.8，手机是红米k30，客户端是安卓1.0 604b442，
局域网使用，视频显示很慢包括视频信息显示也慢，播放视频的都会缓冲
![Screenshot_2024-06-03-21-08-23-981_top ourfor app](https://github.com/ourfor/iPlay/assets/64182739/c9cd6b32-7f01-42c6-a8b2-a065f543f796)

**Comment by ourfor** [comment]
关闭服务器转码功能看看

**Comment by ourfor** [comment]
> 服务端是emby4.8，手机是红米k30，客户端是安卓1.0 [604b442](https://github.com/ourfor/iPlay/commit/604b4422e7695f87a540f15803f07c1ac824bdaa)， 局域网使用，视频显示很慢包括视频信息显示也慢，播放视频的都会缓冲 ![Screenshot_2024-06-03-21-08-23-981_top ourfor app](https://private-user-images.githubusercontent.com/64182739/336084470-c9cd6b32-7f01-42c6-a8b2-a065f543f796.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODcyOTYsIm5iZiI6MTcxNzQ4Njk5NiwicGF0aCI6Ii82NDE4MjczOS8zMzYwODQ0NzAtYzljZDZiMzItN2YwMS00MmM2LWE4YjItYTA2NWY1NDNmNzk2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA3NDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MWRlYzYzMTMwN2RkMTdmNmNiZTY3YWI0Mzk2ZGMzMDQ1NTRjNWRjZDI2YWRkZWFkZDVjZTkyZWRmMTczYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r6WxyBkA_kN_84gzMcgUhwdS0tjoKi7yXJwcdzHb8Jk)

web页面能正常显示封面吗，看着可能是emby缓存的问题

**Comment by make858** [comment]
没用我清理了缓存，还是没有解决

**Comment by make858** [comment]
> > 没用我清理了缓存，还是没有解决
> 
> 换重构后的版本试试，在GitHub主页的Release处可以下载

重构版点剧集类视频直接闪退，电影没有问题
