### ISSUE TITLE
显示登陆失败无法找到与此错误代码关联的文本

### ISSUE THREAD

**Issue by lin0kin** [ourfor/iPlay#159]
没有打开代理工具

![image](https://github.com/ourfor/iPlay/assets/30078096/9ef80f82-9209-41e7-86c9-67b31a15abcf)

**Comment by ourfor** [comment]
> 没有打开代理工具
> 
> ![image](https://private-user-images.githubusercontent.com/30078096/337855081-9ef80f82-9209-41e7-86c9-67b31a15abcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjExMDcsIm5iZiI6MTcxNzg2MDgwNywicGF0aCI6Ii8zMDA3ODA5Ni8zMzc4NTUwODEtOWVmODBmODItOTIwOS00MWU3LTg2YzktNjdiMzFhMTVhYmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDE1MzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTYyZWFiM2UwMDYzYjBmMzNlYmVmNDRlNzA4ODk2Zjc4ZDlhYjlhOGUwNzk4MTI0Mzk2ZTk4YWE0YmNlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GIVRRiYJKJG5SDbDlgG7G9NJQ7UMZncIe4eQ3tTY-fc)

这个是内网地址吧，网上找一下接触UWP网络隔离
