### ISSUE TITLE
安卓jellyfin不能播放

### ISSUE THREAD

**Issue by wxrbbs** [ourfor/iPlay#241]
谢谢支持安卓和jellyfin，下载安装后可以登入浏览，目前不能播放任何视频，是个案？
jellyfin服务端10.8.13 ，cd2挂载本地后strm播放，不管是8096端口播放还是302直连均不能播放。

**Comment by ourfor** [comment]
应该是不能播放，这里还有点问题，后面修一下

**Comment by ourfor** [comment]
问题应该修复了

**Comment by wxrbbs** [comment]
感谢开发者快速修复，已经安装最新版，测试情况如下：1、对于strm 302模式播放经常第一次无法读取播放失败，需要二次重新播放才可以，其它模式也会小概率一次不能播放。2、302模式返回后播放速度有点慢，有待优化提升，是否可以在浏览时候进行预读那些信息（分辨率、音轨、字幕等等）这样会提高302的速度，因为strm播放每次都要读取信息头才可以继续。3、视频全屏问题，怎么操作可以满屏？没看到有切换屏幕大小的按键。最后还是感谢开发者无私奉献，利用业余时间辛苦写代码。
